# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3ef01af0002b5e36a0ec9607064b2015a47c913323a9520d6dd008606d5f4fb53c3bff0cba72c5af1de5242b0853c9aa5e914a8b2885a76c6a360e1b20fa86e

test:
  secret_key_base: 8a673d32007b902ab468f34ac16a71278ab078c63e857e97f68abadf835162e157d853b615ab7bf0abc897a7e5351da26db5624905ce0c8aa205a7a420bbb013

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
