# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56709f3cfa17ec5a9531007f359c68960d8ee7acdcf3cbf02a23543afce3f639a4f19ff3d6c1f8262b72d667e1546d4547679cb9aa28c551929fce09d3a14105

test:
  secret_key_base: 559a376e69355fa4d8f277f69ad06c395af2d8709d8eec8fd08bf6b214bc00d14ea9e869ab5257095ebfb977dd1cc4beadf9e00e7845a195a45edba4e0f64ba6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
