# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c80b38a1c3edbc07cae19431bbf393f9c9efa16ee4c8b3cd49f66b82fa4057b395a5620664dc69afd93c48e20522b799283bfbf419df8eae9d70ca930291e97b

test:
  secret_key_base: 638fd589d637941b58c29cae92fd70ddf32bddd54f5fd03abd9d5472371e00ef14fa59011a7b544da50975bc91ef09528b92926c813355e621e8a38c6231c05a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
