# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb18532cac562e81c90a6b801d78bff469ad69602ec76d412ae7511b0d9b424503713c0eef365ad3664b1591d252f799d7d8d0a6464c4eef4889839fe642a3d7

test:
  secret_key_base: 881e1f69e00265b908a42042fdc012486760c362f30ccc5abd8de2317d50d3cbc6dea70304ff1d0d85403862256bc820fc77f1539979fa8b001f8903181a7626

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
